### PR TITLE
Updates to README.md

### PR DESCRIPTION
**Pull request by ronakice**
change link to right options file

### CODE REVIEW

**Comment by ronakice** [comment]
GPU doesn't work in TF 1.16 so might be better to have stricter TF 1.11 requirement

**Comment by ronakice** [comment]
Added fix to run pretrained models, changing unit number of intermediate ouput layer to 128.

**Comment by caoyu-noob** [comment]
Thank you for your suggestions for README. But why did you change the intermediate state dimension in output layer?

**Comment by ronakice** [comment]
Hi @caoyu1991, according to the pretrained model you have given, I think it requires the intermediate dimension of the output layer to be 128. (I tried running with 256 and it gives that as an error.) However, using 128, it works fine!

**Comment by caoyu-noob** [comment]
Sorry, it seems that I made a mistake when generating the pre-training model. I will correct it. Thanks for reminding.

**Comment by ronakice** [comment]
It seems like with 128 dimensions it performs exactly as stated in the paper (At least the dev set) so I don't think you need to worry about training another model and instead just change this to 128.

**Comment by caoyu-noob** [comment]
I have changed the intermediate dimension. Actually I found that 256 is a bit better than 128 so I modified it, but I forgot it is 128 in my submission.

**Pull request closed without merging**
